### PR TITLE
feat(demo): Replicated Style3 demo

### PR DESCRIPTION
**Pull request by sc231997**
I have added the sample code for Style3 from pdfmake playground

### CODE REVIEW

**Comment by arivera12** [comment]
Hi @sc231997 

I will be reviewing this in a few hours today if I have time for it. 

Do you want to take ownership of this issue https://github.com/arivera12/PdfMakeNet/issues/1 ? 

Please let me know.

And thanks again for your contribution.

**Comment by sc231997** [comment]
Hi @arivera12 ,

I will be happy to take the ownership.

**Comment by arivera12** [comment]
The .gif have no priorities at this moment. 

We will make the .gif at the end after everything is well documents and examples are up and running.

I send you an invite to become a direct collaborator in this repository.

**Comment by arivera12** [comment]
After you accept the invitation I think you can auto assign the issue https://github.com/arivera12/PdfMakeNet/issues/1

**Comment by arivera12** [comment]
I have reviewed the code visually and seems ok. Merged!

**Pull request merged**
