### PR TITLE
feat(demo) #1

### PR DESCRIPTION
**Pull request by sc231997**
For issue #1

### CODE REVIEW

**Comment by sc231997** [comment]
@arivera12  sure i will add those changes. 

I have added one more class `PdfMakeTexts` where the `text` member variable can hold the value as list. Should i add this to header and footer as well.

**Comment by arivera12** [comment]
> @arivera12 sure i will add those changes.
> 
> I have added one more class `PdfMakeTexts` where the `text` member variable can hold the value as list. Should i add this to header and footer as well.

Generally speaking about PdfMake and how it works we could just simply add some methods called:
 
```
AddBody<T>(T pdfmakeObject)
AddHeader<T>(T pdfmakeObject)
AddFooter<T>(T pdfmakeObject)
```

where T could be a string or any pdfmake compatible object.

What you think about this?

I will edit issue https://github.com/arivera12/PdfMakeNet/issues/1 to put some checkbox about the done and pending tasks.

**Comment by sc231997** [comment]
> > @arivera12 sure i will add those changes.
> > 
> > I have added one more class `PdfMakeTexts` where the `text` member variable can hold the value as list. Should i add this to header and footer as well.
> 
> Generally speaking about PdfMake and how it works we could just simply add some methods called:
>  
> ```
> AddBody<T>(T pdfmakeObject)
> AddHeader<T>(T pdfmakeObject)
> AddFooter<T>(T pdfmakeObject)
> ```
> 
> where T could be a string or any pdfmake compatible object.
> 
> What you think about this?
> 
> I will edit issue https://github.com/arivera12/PdfMakeNet/issues/1 to put some checkbox about the done and pending tasks.
> 

I feel doing that way has its own pros and cons.

Pros:
1. It will give the user great flexibility.
2. Less maintenance for us

Cons:
1. This might lead to more runtime exception.
2. It might be different for new users to understand what should be going in there. (We might be able to mitigate this with comment)

 I personally feel having strong type is always good.

Is there any plan to publish this demo site?

**Comment by arivera12** [comment]
> I personally feel having strong type is always good.
> 
> Is there any plan to publish this demo site?

I personally too prefer strong data types as well but it could be just an option where user build any type based on pdfmakenet structure and I think this will give an option to developers to create class templates. I think we should add it anyway.

I never publish demo sites. 

I know github per repository have this option but I have never try it before. 

Do you have done this before. 

I don't any dedicate server purchased at this moment.

**Comment by sc231997** [comment]
> > I personally feel having strong type is always good.
> > 
> > Is there any plan to publish this demo site?
> 
> I personally too prefer strong data types as well but it could be just an option where user build any type based on pdfmakenet structure and I think this will give an option to developers to create class templates structures. I think we should add it anyway.
> 
> I never publish demo sites. 
> 
> I know github per repository have this option but I have never try it before. 
> 
> Do you have done this before?
> 
> I don't any dedicate server purchased at this moment.

Sure, i will add those methods whenever i push my new changes.

Even i have never used GitHub's hosting. We will look at that once we are ready with all the demos.

**Comment by arivera12** [comment]
> Sure, i will add those methods whenever i push my new changes.
> 
> Even i have never used GitHub's hosting. We will look at that once we are ready with all the demos.

Tell me when those changes are added to accept the pull request and keep track of every demo page in separate pull requests.

**Comment by sc231997** [comment]
> > Sure, i will add those methods whenever i push my new changes.
> > 
> > Even i have never used GitHub's hosting. We will look at that once we are ready with all the demos.
> 
> Tell me when those changes are added to accept the pull request and keep track of every demo page in separate pull requests.

Those changes are added now.

Also in this pull request 4 demo codes are also present:
- style2
- columns
- margin
- image

**Comment by arivera12** [comment]
> > > Sure, i will add those methods whenever i push my new changes.
> > > Even i have never used GitHub's hosting. We will look at that once we are ready with all the demos.
> > 
> > 
> > Tell me when those changes are added to accept the pull request and keep track of every demo page in separate pull requests.
> 
> Those changes are added now.
> 
> Also in this pull request 4 demo codes are also present:
> 
> * style2
> * columns
> * margin
> * image

I making the last review I will be pull the changes.

**Pull request merged**
